name: test
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  linux:
    runs-on: ubuntu-latest
    container: ubuntu:rolling
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          ls -la
          ls -la lib
          apt update && apt install -y sudo git
          sudo apt update
          sudo apt -y install make git
      - name: Init
        run: |
          git clone https://github.com/tubav/Core.git lib
          DEBIAN_FRONTEND=noninteractive make deps-lin
      - name: Debug
        run: |
          make debug
      - name: Test
        run: |
          make quick
          make bib
          make all
          echo "testme"|make rename
          make quick
          file testme.pdf
      - name: Show Log
        run: cat build.sh.log
        if: always()
  mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          ls -la
          ls -la lib
      - name: Init
        run: |
          git clone https://github.com/tubav/Core.git lib
          brew install mactex plantuml graphviz gnuplot aspell r
          eval "$(/usr/libexec/path_helper)"
          sudo tlmgr update --self||:
          sudo tlmgr update --all||:
          sudo tlmgr install texliveonfly glossaries biber collection-fontsrecommended IEEEtran xindy
      - name: Debug
        run: |
          eval "$(/usr/libexec/path_helper)"
          make debug
      - name: Test
        run: |
          eval "$(/usr/libexec/path_helper)"
          make quick
          make bib
          make all
          echo "testme"|make rename
          make quick
          file testme.pdf
      - name: Show Log
        run: cat build.sh.log
        if: always()
